Added bash interpreter Indented die function and sudo if statement for easier reading Updated spelling issue on acpi file check Added max_brightness to file check path to verify it exists Rewrote file path checks to match other if statement structures

diff --git a/bright b/bright
--- a/bright
+++ b/bright
@@ -1,23 +1,24 @@
+#!/bin/bash
+
 die(){
-echo $@
-exit 1
+	echo $@
+	exit 1
 }
 
 [ $EUID -ne 0 ] && {
-sudo $0 $@
-exit $?
+	sudo $0 $@
+	exit $?
 }
 [ $# -ne 1 ] && die "USAGE: bright <percentage>"
-[ $1 -gt 0 ] && [ $1  -le 100 ] || die "Percentage must be an integer between 0 and 100 (inclusive)."
+[ $1 -gt 0 ] && [ $1  -le 100 ] || die "Percentage must be an integer between 1 and 100 (inclusive)."
 
-brightness_directory="/dev/null"
-if [ -d /sys/class/backlight/intel_backlight ]; then
+brightness_directory=""
+[ -f /sys/class/backlight/intel_backlight/max_brightness ] && {
 	brightness_directory="/sys/class/backlight/intel_backlight"
-elif [ -d /sys/class/blacklight/acpi_video0 ]; then
+} || [ -f /sys/class/backlight/acpi_video0/max_brightness ] && {
 	brightness_directory="/sys/class/backlight/acpi_video0"
-else
-	die "Can't determine backlight controller"
-fi
+} || die "Can't determine backlight controller"
+
 
 max_brightness="`cat $brightness_directory/max_brightness`"
 brightness=$(expr 100 / $1)
